### ISSUE TITLE
Feature Request: Support to receive messages with multiple pictures

### ISSUE THREAD

**Issue by Blackoverflow** [nanu-c/textsecure-qml#83] opened 2019-10-15 13:35 UTC
Since quite some time, signal supports to sent multiple pictures in one message.
This client does not and shows only one picture. There is no hint that I got multiple pictures.

I would like to see all pictures that were sent. Maybe by splitting the message?
I don't need the feature to send multiple pictures at once, though.

If that isn't possible, is it possible to at least warn about the lost pictures?

This request has no high priority.

**Comment by kallekruse** [comment] 2019-10-23 19:15
Duplicate of #58 ?

**Comment by yo-k** [comment] 2019-10-24 19:36
@kallekruse Yes, I think it is a duplicate, too. It's not only an enhancement but also a bug. The bug hopefully disappears with the enhancement ;-)

**Closed by yo-k** 2019-10-24 19:36 UTC
Labels: duplicate, enhancement

**Comment by paugier** [comment] 2019-12-17 20:32
I also experience this behavior (which is quite different than #58).

Here, we indeed see a message with only one picture whereas in #58 "The message never appeared in the conversation."
