### ISSUE TITLE
limit at 20 messages per contact

### ISSUE THREAD

**Issue by yo-k** [nanu-c/textsecure-qml#95] opened 2019-11-09 22:37 UTC
### Description
There seems to be a limit of 20 messages per contact / group. New messages are received and displayed, but older ones disappear. Only the last 20 are displayed.

### Steps to Reproduce
1. ask someone to send you more than 20 messages. Very short messages are completely sufficient.
2. count the messages.

another small feature:
if the contact is already open, more messages will be displayed. But only until the contact is reopened, then there are only 20.

**Expected behavior:** 
I expect all incoming messages to be displayed permanently.

**Actual behavior:** 
A maximum of 20 messages are displayed when a contact is opened.

#### Versions
axolotl 0.7.0 ota-11

#### Device
bq e4.5

**Comment by oberling** [comment] 2019-11-11 07:22
I can confirm but wouldn't expect them to be displayed permanently. It would suffice to be load them from the database when scrolling up if the UI item is not able to show the bottom of the list fast enough when the number of  messages rises...

**Comment by nanu-c** [comment] 2019-11-11 09:15
once upon a time, scrolling up was detected and triggering loading more messages...

**Comment by nanu-c** [comment] 2019-11-19 10:15
fixed in aa3813f8d115f370acf8d696bf4364ee5239a37f

**Closed by nanu-c** 2019-11-19 10:15 UTC
Labels: bug

**Comment by oberling** [comment] 2019-12-20 17:25
Scrolling up now reveals older messages but also shows the recent onces at least twice (I thought I saw them multiple times too but cannot reproduce this currently).
also the scroll position is not kept after loading older messages...
