### ISSUE TITLE
Debug mode (displayed as) deactivated 

### ISSUE THREAD

**Issue by kallekruse** [nanu-c/textsecure-qml#49] opened 2019-01-12 21:15 UTC
### Description

I have been observing a recurring issue with the the app: After some weeks / months of (quite heavy) usage the app starts crashing, reliably some seconds after start. The only workaround I have found until now is a completely clean reinstall, after removing all data of the app (very annoying because this way my complete chat history gets lost and I have to ask to be re-added to all groups). I would like to create a bug report for this issue but assume that logs are needed for finding the cause. I have tried to activate the debug mode but after each app restart it gets displayed as inactive.

### Steps to Reproduce

1. Go to Setting and activate debug mode
2. Restart app
3. Go to Settings and check debug mode is still activated

**Expected behavior:** Still activated.

**Actual behavior:** Displayed as inactive. Not sure if this is a display problem only or if the debug mode gets in fact deactivated (or even has been activated at all). 

**Reproduces how often:** always

### Additional Information

Also reported by @timothymctim here: https://github.com/nanu-c/textsecure-qml/issues/34#issuecomment-392330090

How can I determine if the debug mode gets activated at all?

#### Versions

> Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`

Cannot find this menu entry.

#### Device

bq Aquarius 4.5
OTA-6

#### Link to Debug Log

> Please provide the link generated by `Settings->Advanced-> Submit Debug Log`

Not possible, see above.

**Comment by 1ploss** [comment] 2019-03-07 20:07
I can confirm that the toggle is not initialized correctly if debug mode is activated.
The loglevel is correct, as visible in /home/phablet/.config/textsecure.nanuc/config.yml

**Comment by yo-k** [comment] 2019-10-21 18:02
There is no button to activate or deactivate anymore. I think this ticket in this form is obsolete since newer versions of axolotl signal.

axolotl 0.7.0 bq e4.5 ota10

Close this ticket?

**Comment by nanu-c** [comment] 2019-10-21 20:19
Yup please

**Closed by nanu-c** 2019-10-21 20:19 UTC
