### ISSUE TITLE
Linked Devices causes crash

### ISSUE THREAD

**Issue by theBest3000** [nanu-c/textsecure-qml#41] opened 2018-11-03 08:43 UTC
### Description

Pressing "Linked Devices" crashes the app.

### Steps to Reproduce

1. Open application
2. `Burger menu -> Settings ->Linked Devices`

**Expected behavior:** Asking for access permission to the camera application.

**Actual behavior:** Application crashes.

**Reproduces how often:** 100% (all the time)

#### Versions

Signal 0.3.261

#### Devices
BQ Aquaris E4.5 
BQ Aquaris M10 HD
#### Link to Debug Log
Please provide the link generated by `Settings->Advanced-> Submit Debug Log` (this also does not work. I do not know if this is a general problem with pasting in current UBPort version or a problem with the signal application.)

Logviewer information:

http://paste.ubuntu.com/p/FFmkfdsgNq/

**Comment by nanu-c** [comment] 2019-01-13 21:14
I can't reproduce this anymore. Can I close it?

**Comment by theBest3000** [comment] 2019-01-15 06:11
The bug is gone at my E4.5 but unfortunately still there at my M10 HD.

**Comment by nanu-c** [comment] 2019-01-16 16:21
is your m10 hd on xenial or on vivid?

**Comment by theBest3000** [comment] 2019-01-18 12:58
its on xenial

**Comment by nanu-c** [comment] 2019-10-21 09:00
I redesigned the syncing process and you have to use tagger now, so i close this issue

**Closed by nanu-c** 2019-10-21 09:00 UTC
Labels: bug
